version: '3.1'
services:
  frontend:
    image: frontend/thigio-poc/Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend

  backend:
    image: backend/Dockerfile
    ports:
      - "4000:4000"
    container_name: backend