version: '3'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    container_name: backend
